Resources:
  Ec2Instance: # Logical ID
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-5b41123e # AMI ID for us-east-1
      Tags:
        - Key: "Name"
          Value: "JonSnowCloudFormation"
        - Key: "User"
          Value: !Join [" ", ["cloud-formation-user", "is", "a", "CloudFormation", "admin" ]]