Resources:
  KaliSecurityGroup: # Logical ID
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: JonSnowCloudFormation
        - Key: TestPseudoParam
          Value: !Join # use Join as Intrinsic function
            - ""
            - - "SecurityGroup for "
              - !Ref AWS::Region # use Pseudo param for Region