Mappings: # map regions
  RegionMap:
    us-east-1:
      AMI: ami-1853ac65
    us-west-1:
      AMI: ami-bf5540df
    eu-west-1:
      AMI: ami-3bfab942
    ap-southeast-1:
      AMI: ami-e2adf99e
    ap-southeast-2:
      AMI: ami-43874721
Resources:
  KaliEc2Instance:  # Logical ID
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: # define imageId based on region
        Fn::FindInMap:  # use Intrinsic function
        - RegionMap # map name
        - !Ref AWS::Region  # top level key, use Pseudo param for Region
        - AMI # second level key
      SecurityGroups: 
        - !Ref KaliSecurityGroup # Refer to SecurityGroup that will be created
      Tags:
        - Key: MapRegionTag
          Value: !Join # use Intrinsic function
            - ""
            - - "EC2 Instance for "
              - !Ref AWS::Region
        - Key: Name
          Value: JonSnowCloudFormation      
  KaliSecurityGroup:  # Logical ID
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: JonSnowCloudFormation